version: '3'

services:
    django:
        build: .
        container_name: txns_container
        image: tokka_txns_challenge:latest
        env_file:
            - .env
        command: bash -c "
            python manage.py initialize_db &&
            python manage.py runserver 0.0.0.0:8000"
        depends_on:
            - timescaledb
        network_mode: host

    realtime_service:
        build: .
        container_name: realtime_record_container
        image: tokka_txns_challenge:latest
        env_file:
            - .env
        command: bash -c "
            python manage.py initialize_db &&
            python manage.py realtime_record"
        depends_on:
            - timescaledb
        network_mode: host

    batch_service:
        build: .
        container_name: batch_record_container
        image: tokka_txns_challenge:latest
        env_file:
            - .env
        depends_on:
            - timescaledb
        network_mode: host

    django_test:
        build: .
        container_name: django_test_container
        image: tokka_txns_challenge:latest
        env_file:
            - .env
        depends_on:
            - timescaledb
        network_mode: host

    pgadmin:
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
            PGADMIN_LISTEN_PORT: 5050
        depends_on:
            - timescaledb
        network_mode: host

    timescaledb:
        image: timescale/timescaledb:latest-pg14
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - timescaledb_data:/var/lib/postgresql/data  # Persist database between container restarts
        network_mode: host

volumes:
    timescaledb_data:
